const mongoose = require('mongoose');

/**
 * PaymentLink — a one-time, shareable link that lets a parent/guardian
 * pay a specific fee without logging into the system.
 *
 * Generated by the school admin; shared via WhatsApp/SMS.
 * Valid for 7 days. Invalidated after one successful payment.
 */
const paymentLinkSchema = new mongoose.Schema(
  {
    school_id: { type: mongoose.Schema.Types.ObjectId, ref: 'School', required: true },
    fee_id:    { type: mongoose.Schema.Types.ObjectId, ref: 'Fee',    required: true },

    /** 32-character hex token — the public URL identifier */
    token: { type: String, required: true, unique: true },

    /** Amount at link-generation time (= fee.due_amount) */
    amount: { type: Number, required: true, min: 0 },

    status: {
      type: String,
      enum: ['active', 'used', 'expired'],
      default: 'active',
    },

    expiresAt: {
      type: Date,
      default: () => new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // +7 days
    },
  },
  { timestamps: true }
);

paymentLinkSchema.index({ fee_id: 1 });
paymentLinkSchema.index({ school_id: 1, status: 1 });

module.exports = mongoose.model('PaymentLink', paymentLinkSchema);
